### ISSUE TITLE
The "ResolveAssemblyReference" task failed unexpectedly.

### ISSUE THREAD

**Issue by twhall-umich** [microsoft/Xaml-Islands-Samples#32]
I updated to Windows 2004 and this is going from bad to worse.  Now the build fails:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "ResolveAssemblyReference" task failed unexpectedly.
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Unexpected CopyLocal flag.
   at Microsoft.Build.Tasks.CopyLocalStateUtility.IsCopyLocal(CopyLocalState state)
   at Microsoft.Build.Tasks.ResolveAssemblyReference.LogResults(ReferenceTable dependencyTable, List`1 idealAssemblyRemappings, List`1 idealAssemblyRemappingsIdentities, List`1 generalResolutionExceptions)
   at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute(FileExists fileExists, DirectoryExists directoryExists, GetDirectories getDirectories, GetAssemblyName getAssemblyName, GetAssemblyMetadata getAssemblyMetadata, GetRegistrySubKeyNames getRegistrySubKeyNames, GetRegistrySubKeyDefaultValue getRegistrySubKeyDefaultValue, GetLastWriteTime getLastWriteTime, GetAssemblyRuntimeVersion getRuntimeVersion, OpenBaseKey openBaseKey, GetAssemblyPathInGac getAssemblyPathInGac, IsWinMDFile isWinMDFile, ReadMachineTypeFromPEHeader readMachineTypeFromPEHeader)
   at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	MyApp	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	2084	
```

**Comment by twhall-umich** [comment]
I grabbed a clean clone and started to apply NuGet updates on-by-one to try to isolate the cause of my problems.

*  Microsoft.UI.Xaml v2.3.191125001 - prerelease => v2.4.3:  When I started with just this one update, I got the same build error: The "ResolveAssemblyReference" task failed unexpectedly.

So I started over with another clean clone:

*  Microsoft.VCRTForwarders.140 v1.0.4 => v1.0.6: OK
*  Microsoft.Windows.ImplementationLibrary v1.0.200519.2 => v1.0.200902.2: OK
*  Microsoft.Windows.CppWinRT v2.0.191111.2 => v2.0.201008.2: OK
*  Microsoft.UI.Xaml: v2.3.191125001 - prerelease => v2.4.3: OK when I did this last, or at least did it with all of the others.

I am mystified.
